### ISSUE TITLE
HL: Alyx - Broken textures

### ISSUE THREAD

**Issue by oneohtrix** [SteamDatabase/ValveResourceFormat#202]
### Describe the bug
There seems to be an issue with loading (or rendering) textures.

`*_color_*` textures seem to be using a new image type `BC7`, which hasn't been implemented yet.

```
System.NotImplementedException: Unhandled image type: BC7
   at ValveResourceFormat.ResourceTypes.Texture.GenerateBitmap() in C:\projects\valveresourceformat\ValveResourceFormat\Resource\ResourceTypes\Texture.cs:line 355
   at GUI.MainForm.ProcessFile(String fileName, Byte[] input, TreeViewPackageTag currentPackage) in C:\projects\valveresourceformat\GUI\MainForm.cs:line 525
```

When trying to open up a `.vmdl_c` file, the model gets rendered, however the `*.vmat_c` causes it to be "spotty" (missing pieces of the texture). 

------ 

### Reference file in a Valve game

HLVR:  
`pak01_001.vpk/models/characters/metrocop/metrocop_choreo.vmdl_c`
![image](https://user-images.githubusercontent.com/8982584/77354789-aa8fab00-6d43-11ea-822e-8a4b9015ff15.png)

`pak01_001.vpk/models/characters/metrocop/materials/metrocop_body.vmat_c`
![image](https://user-images.githubusercontent.com/8982584/77354761-a2377000-6d43-11ea-9f16-281460ec229e.png)

### Expected behavior
The expected behavior is to display the whole texture, not just bits of it.

### Version info

Latest unstable build - 0.1.2.1072 (3/23/2020 6:42:41 PM) - Windows 10 (Version 1909)

**Comment by xPaw** [comment]
> BC7, which hasn't been implemented yet.

It is on master, you can try that. But it's not related to the rendering issues.

**Comment by xPaw** [comment]
> Unhandled image type: BC7

It is implemented on master.

I fixed the spotty models/materials on master just now.

**Comment by CodeF53** [comment]
Thanks for the commit, but after recompiling the source and putting the newly compiled .dll into the VRF folder (overwriting the old one), the issue still persists!
![image](https://user-images.githubusercontent.com/37855219/77381424-774d1c00-6d43-11ea-94ca-1397867ceaa3.png)

**Comment by xPaw** [comment]
Grab the build from appveyor, you need all files recompiled not just some DLL.
