### ISSUE TITLE
gltf armature rotation problem.

### ISSUE THREAD

**Issue by Zony-Zhao** [SteamDatabase/ValveResourceFormat#360]
### Describe the bug

The gltf armature is not compatible with Source film maker animation.
may be due to bone rotation axis wrong.

### What Valve game does this happen in

Dota2

### Reference file in a Source 2 game

dota2 =>pak01_dir.vpk=>shopkeeper.vmdl_c
I use SFM =>create animationset for model=>choose shopkeeper => import animation=>export animation.
In Blender, import gltf(compiled from vmdl_c)=>import animation(export from SFM). Then I got some creepy mesh.

### Expected behavior

The animation should work well on gltf model
When I use model from https://www.dota2.com/workshop/requirements/sniper(FBX) with SFM exported animation, everything goes well.
But when I use gltf model compiled from VRF, problem happens. 

### What version of VRF are you using? On what platform?

commit 67ce3e4dbf0528f9d2f0ee507070d0431a90303d (HEAD -> master, origin/master, origin/HEAD) Author: Pavel Djundik <xPaw@users.noreply.github.com> Date:   Tue Jun 29 17:09:06 2021 +0300. Win10

### more info:
Model :
![image](https://user-images.githubusercontent.com/50739849/124423636-21fe1800-dd98-11eb-8a32-13d17dad8562.png)
Animation:
![image](https://user-images.githubusercontent.com/50739849/124423665-3510e800-dd98-11eb-87da-48edc5491d62.png)
Import gltf in Blender:
![image](https://user-images.githubusercontent.com/50739849/124424001-d304b280-dd98-11eb-8df3-7a2dbe03646d.png)

Import animation in Blender:
![image](https://user-images.githubusercontent.com/50739849/124423701-4954e500-dd98-11eb-9d8f-ad71ca649054.png)

### my guess:
This is SFM armature visualization:
![image](https://user-images.githubusercontent.com/50739849/124424342-735ad700-dd99-11eb-9f57-70573de268fe.png)
This is gltf armature in Blender:
![image](https://user-images.githubusercontent.com/50739849/124424452-a00eee80-dd99-11eb-894d-bb353b6aa226.png)
The general shape is right, but the bone in gltf may have some rotation issue?

**Comment by xPaw** [comment]
Try latest build, this was possibly fixed by cfae01a0eec50d1c973d51ce2a0b47977b447c63

**Comment by Zony-Zhao** [comment]
> Try latest build, this was possibly fixed by [cfae01a](https://github.com/SteamDatabase/ValveResourceFormat/commit/cfae01a0eec50d1c973d51ce2a0b47977b447c63)

Thanks for you guys' work. Will test ASAP and reply here

**Comment by Zony-Zhao** [comment]
Still not work in newer release.
![image](https://user-images.githubusercontent.com/50739849/124447287-cc376900-ddb3-11eb-8f20-e5d4daba44d1.png)
![image](https://user-images.githubusercontent.com/50739849/124447312-d0638680-ddb3-11eb-9326-c91f62167e65.png)

**Comment by xPaw** [comment]
I don't know, it worked for me. Did you rebuild properly? Download a build from CI.

![image](https://user-images.githubusercontent.com/613331/124447780-5f5ba900-dd8a-11eb-9f43-0e548bd39875.png)

**Comment by Zony-Zhao** [comment]
I don't know how to download from CI. All I know is git pull. Can you give me some guide?

**Comment by xPaw** [comment]
There's a link on https://vrf.steamdb.info/ under the big download button.

**Comment by Zony-Zhao** [comment]
I get the latest unstable build.
![image](https://user-images.githubusercontent.com/50739849/124449568-2a654b80-ddb6-11eb-98f5-62820aeb119d.png)
![image](https://user-images.githubusercontent.com/50739849/124449982-91830000-ddb6-11eb-8ceb-2319f7064413.png)

The gltf **is** OK when imported, but **not compatible** with the exported animation. I attach the animation file in the last comment. Please try it out.

**Comment by Perryvw** [comment]
As far as I understand the GLTF correctly exports and imports into blender, but when applying a SFM animation it somehow breaks. I have no clue how SFM animations work or what plugin you are using to load/apply them to our skeletons.

While I think that in theory it could be possible to make them compatible, that depends on:
1) Our code
2) Our gltf exporting library
3) Blender's gltf importing plugin
4) Blender's SFM animation plugin.

We only know number 1 here, so I doubt we will be able to support this.

**Comment by Zony-Zhao** [comment]
Thanks to @Perryvw  clearly pointing out the problem.I got it solved!
Since there are so many export import process in this, with so many plugin im/export options, I have a strong feeling that it is a axis problem( the animation bones are somehow perpendicular to the original ones)
It turns out to be Blender gltf plugin, should use this option:
Bone Dir:'Blender'
It says 'Blender' is for re-importing, so I didn't choose it, however it is the answer for this.( maybe blender gltf use the same lib as VRF does)
![image](https://user-images.githubusercontent.com/50739849/124455218-e37a5480-ddbb-11eb-9cb7-26fa8690721f.png)
After you import the gltf, the armature should look like this:( bones are perpendicular to the body, **INSTEAD OF** following along the body mesh).
And then import the animation:(still, perpendiocular)
![image](https://user-images.githubusercontent.com/50739849/124456169-fb060d00-ddbc-11eb-8676-ce386ea53958.png)
The SFM GUI visualizer is a little bit misleading though, pointing us to a wrong direction. 

Really appreciate your fast reply! And This project is amazing work!  I think it is ok to close this issue.
